$axure.loadCurrentPage({
  "url":"企业展示－概览.html",
  "generationDate":new Date(1400740445359.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5005b223ccd8492eaba224e6ee1acde0",
    "type":"Axure:Page",
    "name":"企业展示－概览",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d109f707c0164f0a9c3d72027ce055a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":64},
            "size":{
              "width":1439,
              "height":58},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dda7621d7f934603b373398af843a116",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":64},
                "size":{
                  "width":1439,
                  "height":58},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u0.png"}},
{
          "id":"8c809d8cae8a408e99010788327832cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":3},
            "size":{
              "width":1439,
              "height":61},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca882fdea57b40719f519e42d6631347",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2,
                  "y":3},
                "size":{
                  "width":1439,
                  "height":61},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u2.png"}},
{
          "id":"ce20e9b198c24f1dad7515b3ce184fd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":446,
              "y":157},
            "size":{
              "width":689,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95bf0c8db95b4f3fb5f7d7aadc9423cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":446,
                  "y":157},
                "size":{
                  "width":689,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b18bea4fe064021a5402c1c66d43263",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":251},
            "size":{
              "width":964,
              "height":3},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88745999f32d40dc8d47dc8e07685455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":251},
                "size":{
                  "width":964,
                  "height":3},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u12.png"}},
{
          "id":"99a8564fb5984caf8c68a9dc4445dac8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":618},
            "size":{
              "width":251,
              "height":306},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f808494d45242c78f7a9847c722a795",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":618},
                "size":{
                  "width":251,
                  "height":306},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u18.png"}},
{
          "id":"26e7a1209d3e418aa29d32413aa9cd26",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":229,
              "y":266},
            "size":{
              "width":248,
              "height":105},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bca82cb9081242eda41faafd2dbed993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":229,
                  "y":266},
                "size":{
                  "width":248,
                  "height":105},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u20.png"}},
{
          "id":"32ea00d392404b7db17f7d72c6267cf5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":226,
              "y":926},
            "size":{
              "width":255,
              "height":55},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8ba5dabc99c48808c097accf5a5a163",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":926},
                "size":{
                  "width":255,
                  "height":55},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u22.png"}},
{
          "id":"3e15a7af3a234556861b6be5147e6148",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":986},
            "size":{
              "width":1376,
              "height":105},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d015a4675464e5f902101f74bd3f6a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":986},
                "size":{
                  "width":1376,
                  "height":105},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u26.png"}},
{
          "id":"c6a13b31f91549d4be7d5c6e93a3e46c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1310,
              "y":985},
            "size":{
              "width":133,
              "height":107},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4c56e06873d4abfb6e226d556372871",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1310,
                  "y":985},
                "size":{
                  "width":133,
                  "height":107},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u28.png"}},
{
          "id":"e6675dd1dd1e4f0690e246e5a9fab3cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":3},
            "size":{
              "width":1009,
              "height":117}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39ed945eeb2241db8ae94b2e1f9606f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":3},
                "size":{
                  "width":1009,
                  "height":117}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u30.png"}},
{
          "id":"3f338b76fb254f1aa2f783019462b86e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":415},
            "size":{
              "width":252,
              "height":197},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff0aa685cf26414ba3779880665f4ca0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":415},
                "size":{
                  "width":252,
                  "height":197},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u32.png"}},
{
          "id":"a270935a1fa644968e9eba51a0d48dab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'黑体 Regular', '黑体'",
            "fontSize":"28px",
            "location":{
              "x":237,
              "y":82},
            "size":{
              "width":353,
              "height":32},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e640c31452c4ea99c7e1e345744d21b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'黑体 Regular', '黑体'",
                "fontSize":"28px",
                "location":{
                  "x":237,
                  "y":82},
                "size":{
                  "width":353,
                  "height":32},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bc915adb70a46cd8d9c89b16e957c99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":748,
              "y":30},
            "size":{
              "width":52,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74eb364dfc3c44b3a772083c907ac72d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":748,
                  "y":30},
                "size":{
                  "width":52,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 科特派服务角 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"科特派服务角.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"544c310322e74dbd8c16bc7020fc90ee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":379},
            "size":{
              "width":255,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b68b455f07024f3fa71e27e572e79b13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":379},
                "size":{
                  "width":255,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u44.png"}},
{
          "id":"06243bb453cc4c5892879b9dc8368fff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":477,
              "y":256},
            "size":{
              "width":713,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0347d5700ab847659e382b9697dd92fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":477,
                  "y":256},
                "size":{
                  "width":713,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成果展示－概览/u30.png"}},
{
          "id":"7215c6d3c11f441ca711b3cc22e325e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":943,
              "y":263},
            "size":{
              "width":245,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5653624dd4d456684de0933e3a585e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":943,
                  "y":263},
                "size":{
                  "width":245,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u46.png"}},
{
          "id":"ceb84cac52034f468df3a776305a6333",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":495,
              "y":958},
            "size":{
              "width":695,
              "height":6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfae678ca25941f09c2c0eb533320202",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":495,
                  "y":958},
                "size":{
                  "width":695,
                  "height":6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成果展示－概览/u42.png"}},
{
          "id":"f23f000f6fd54aa4a3792e0081193faf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1070,
              "y":335},
            "size":{
              "width":92,
              "height":95}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70bc2e9f63ac49c29aa35c2a4207c1c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1070,
                  "y":335},
                "size":{
                  "width":92,
                  "height":95}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 成果展示－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"成果展示－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fed9b574f40b48cd9c2e92ed8f9c7443",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":949,
              "y":26},
            "size":{
              "width":61,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1861608a5a4481aacc5fded0df825d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":949,
                  "y":26},
                "size":{
                  "width":61,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f807fe8dc0e4da6a304d4d5820099e1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":120},
            "size":{
              "width":131,
              "height":126}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41ab336dfb9b4140bbc49dbfa2b19187",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":120},
                "size":{
                  "width":131,
                  "height":126}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/企业展示－概览/u38.png"}},
{
          "id":"3ab740e4004845b7b5098eca8b51780f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":488,
              "y":310},
            "size":{
              "width":712,
              "height":470}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6b6411ec0014a158562e399b610c580",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":488,
                  "y":310},
                "size":{
                  "width":712,
                  "height":470}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/企业展示－概览/u40.png"}},
{
          "id":"4d19ede0f74b4a009596325e330d599d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":488,
              "y":778},
            "size":{
              "width":712,
              "height":194}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38af5ba3326b42d1912fcfb2ef9a0506",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":488,
                  "y":778},
                "size":{
                  "width":712,
                  "height":194}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/企业展示－概览/u42.png"}},
{
          "id":"7c16da89d4d144d7a781618528763a50",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":326},
            "size":{
              "width":292,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"464f972779d745658e1e5b324780800f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":326},
                "size":{
                  "width":292,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 企业展示－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"企业展示－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a65499ac1ad48d4aa23cb29ff1d6062",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":386},
            "size":{
              "width":292,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"738e67e9b51c49bbae61f6e3adb14f0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":386},
                "size":{
                  "width":292,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 企业展示－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"企业展示－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"606049bbf00f43f9ba4171983f9d8264",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":878,
              "y":386},
            "size":{
              "width":292,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79d120cd7d3841598480d91b3e1188aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":878,
                  "y":386},
                "size":{
                  "width":292,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 企业展示－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"企业展示－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d460c456f5fe488aa74a1f327caa8cb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":548,
              "y":356},
            "size":{
              "width":292,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4944848c15f426aaf3b7ba29d77b029",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":548,
                  "y":356},
                "size":{
                  "width":292,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 企业展示－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"企业展示－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d95a2ec1393434c8e0b3a9ab33872a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":528,
              "y":456},
            "size":{
              "width":292,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffdf9fa8eeb04d1aadbc656d818ca964",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":528,
                  "y":456},
                "size":{
                  "width":292,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 企业展示－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"企业展示－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"202bc60abd6e46acb3786bff78b44e24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":878,
              "y":456},
            "size":{
              "width":292,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b53920369c134d17b22b594b3a4bb595",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":878,
                  "y":456},
                "size":{
                  "width":292,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 企业展示－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"企业展示－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c69d7d0e1446415d8786283088142c28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":869.999938964844,
              "y":523},
            "size":{
              "width":292,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61a382e51a5344cb917e7c0450905b15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":869.999938964844,
                  "y":523},
                "size":{
                  "width":292,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 企业展示－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"企业展示－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f1b840c7b3344ce81b19988907ae115",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":523},
            "size":{
              "width":292,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81fd7515b6874b6fb5f4accafff1bbb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":523},
                "size":{
                  "width":292,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 企业展示－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"企业展示－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ae9981e63a64f74987c27ed13b460c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":528,
              "y":586},
            "size":{
              "width":292,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"618e20e4ed504014916d76b01ba18fb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":528,
                  "y":586},
                "size":{
                  "width":292,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 企业展示－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"企业展示－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b32ad159a9344e29bb5a34ab0410996",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":877.999938964844,
              "y":586},
            "size":{
              "width":292,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"697092c2b574400390983dbb80ae3280",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":877.999938964844,
                  "y":586},
                "size":{
                  "width":292,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 企业展示－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"企业展示－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c62a844c88a4a28b90ee4a9e5c49fa4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":878,
              "y":656},
            "size":{
              "width":292,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4be7cf9b4a304a7387d977e3c3cd9bde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":878,
                  "y":656},
                "size":{
                  "width":292,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 企业展示－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"企业展示－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dadda5d1d6054b48b516bf7951d417a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":650},
            "size":{
              "width":292,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae822d17cd89438c9af2b264c1cf128b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":650},
                "size":{
                  "width":292,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 企业展示－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"企业展示－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3b50948b6d445e2a2792b83c8cd5675",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":888,
              "y":716},
            "size":{
              "width":292,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac652bdd9d234b279231d1e62d2ef343",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":888,
                  "y":716},
                "size":{
                  "width":292,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 企业展示－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"企业展示－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e31c6dec41f54bd2b89de5cc17ad8f3e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":266},
            "size":{
              "width":246,
              "height":715}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edf02dbd2f9c4757a038ba25498359f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":266},
                "size":{
                  "width":246,
                  "height":715}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/企业展示－概览/u70.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d109f707c0164f0a9c3d72027ce055a5":{
      "scriptId":"u0"},
    "dda7621d7f934603b373398af843a116":{
      "scriptId":"u1"},
    "8c809d8cae8a408e99010788327832cd":{
      "scriptId":"u2"},
    "ca882fdea57b40719f519e42d6631347":{
      "scriptId":"u3"},
    "ce20e9b198c24f1dad7515b3ce184fd4":{
      "scriptId":"u4"},
    "95bf0c8db95b4f3fb5f7d7aadc9423cd":{
      "scriptId":"u5"},
    "4b18bea4fe064021a5402c1c66d43263":{
      "scriptId":"u6"},
    "88745999f32d40dc8d47dc8e07685455":{
      "scriptId":"u7"},
    "99a8564fb5984caf8c68a9dc4445dac8":{
      "scriptId":"u8"},
    "0f808494d45242c78f7a9847c722a795":{
      "scriptId":"u9"},
    "26e7a1209d3e418aa29d32413aa9cd26":{
      "scriptId":"u10"},
    "bca82cb9081242eda41faafd2dbed993":{
      "scriptId":"u11"},
    "32ea00d392404b7db17f7d72c6267cf5":{
      "scriptId":"u12"},
    "c8ba5dabc99c48808c097accf5a5a163":{
      "scriptId":"u13"},
    "3e15a7af3a234556861b6be5147e6148":{
      "scriptId":"u14"},
    "4d015a4675464e5f902101f74bd3f6a5":{
      "scriptId":"u15"},
    "c6a13b31f91549d4be7d5c6e93a3e46c":{
      "scriptId":"u16"},
    "d4c56e06873d4abfb6e226d556372871":{
      "scriptId":"u17"},
    "e6675dd1dd1e4f0690e246e5a9fab3cb":{
      "scriptId":"u18"},
    "39ed945eeb2241db8ae94b2e1f9606f4":{
      "scriptId":"u19"},
    "3f338b76fb254f1aa2f783019462b86e":{
      "scriptId":"u20"},
    "ff0aa685cf26414ba3779880665f4ca0":{
      "scriptId":"u21"},
    "a270935a1fa644968e9eba51a0d48dab":{
      "scriptId":"u22"},
    "4e640c31452c4ea99c7e1e345744d21b":{
      "scriptId":"u23"},
    "9bc915adb70a46cd8d9c89b16e957c99":{
      "scriptId":"u24"},
    "74eb364dfc3c44b3a772083c907ac72d":{
      "scriptId":"u25"},
    "544c310322e74dbd8c16bc7020fc90ee":{
      "scriptId":"u26"},
    "b68b455f07024f3fa71e27e572e79b13":{
      "scriptId":"u27"},
    "06243bb453cc4c5892879b9dc8368fff":{
      "scriptId":"u28"},
    "0347d5700ab847659e382b9697dd92fe":{
      "scriptId":"u29"},
    "7215c6d3c11f441ca711b3cc22e325e3":{
      "scriptId":"u30"},
    "c5653624dd4d456684de0933e3a585e9":{
      "scriptId":"u31"},
    "ceb84cac52034f468df3a776305a6333":{
      "scriptId":"u32"},
    "bfae678ca25941f09c2c0eb533320202":{
      "scriptId":"u33"},
    "f23f000f6fd54aa4a3792e0081193faf":{
      "scriptId":"u34"},
    "70bc2e9f63ac49c29aa35c2a4207c1c6":{
      "scriptId":"u35"},
    "fed9b574f40b48cd9c2e92ed8f9c7443":{
      "scriptId":"u36"},
    "f1861608a5a4481aacc5fded0df825d2":{
      "scriptId":"u37"},
    "0f807fe8dc0e4da6a304d4d5820099e1":{
      "scriptId":"u38"},
    "41ab336dfb9b4140bbc49dbfa2b19187":{
      "scriptId":"u39"},
    "3ab740e4004845b7b5098eca8b51780f":{
      "scriptId":"u40"},
    "a6b6411ec0014a158562e399b610c580":{
      "scriptId":"u41"},
    "4d19ede0f74b4a009596325e330d599d":{
      "scriptId":"u42"},
    "38af5ba3326b42d1912fcfb2ef9a0506":{
      "scriptId":"u43"},
    "7c16da89d4d144d7a781618528763a50":{
      "scriptId":"u44"},
    "464f972779d745658e1e5b324780800f":{
      "scriptId":"u45"},
    "0a65499ac1ad48d4aa23cb29ff1d6062":{
      "scriptId":"u46"},
    "738e67e9b51c49bbae61f6e3adb14f0c":{
      "scriptId":"u47"},
    "606049bbf00f43f9ba4171983f9d8264":{
      "scriptId":"u48"},
    "79d120cd7d3841598480d91b3e1188aa":{
      "scriptId":"u49"},
    "d460c456f5fe488aa74a1f327caa8cb8":{
      "scriptId":"u50"},
    "a4944848c15f426aaf3b7ba29d77b029":{
      "scriptId":"u51"},
    "0d95a2ec1393434c8e0b3a9ab33872a9":{
      "scriptId":"u52"},
    "ffdf9fa8eeb04d1aadbc656d818ca964":{
      "scriptId":"u53"},
    "202bc60abd6e46acb3786bff78b44e24":{
      "scriptId":"u54"},
    "b53920369c134d17b22b594b3a4bb595":{
      "scriptId":"u55"},
    "c69d7d0e1446415d8786283088142c28":{
      "scriptId":"u56"},
    "61a382e51a5344cb917e7c0450905b15":{
      "scriptId":"u57"},
    "4f1b840c7b3344ce81b19988907ae115":{
      "scriptId":"u58"},
    "81fd7515b6874b6fb5f4accafff1bbb6":{
      "scriptId":"u59"},
    "0ae9981e63a64f74987c27ed13b460c8":{
      "scriptId":"u60"},
    "618e20e4ed504014916d76b01ba18fb6":{
      "scriptId":"u61"},
    "6b32ad159a9344e29bb5a34ab0410996":{
      "scriptId":"u62"},
    "697092c2b574400390983dbb80ae3280":{
      "scriptId":"u63"},
    "5c62a844c88a4a28b90ee4a9e5c49fa4":{
      "scriptId":"u64"},
    "4be7cf9b4a304a7387d977e3c3cd9bde":{
      "scriptId":"u65"},
    "dadda5d1d6054b48b516bf7951d417a9":{
      "scriptId":"u66"},
    "ae822d17cd89438c9af2b264c1cf128b":{
      "scriptId":"u67"},
    "e3b50948b6d445e2a2792b83c8cd5675":{
      "scriptId":"u68"},
    "ac652bdd9d234b279231d1e62d2ef343":{
      "scriptId":"u69"},
    "e31c6dec41f54bd2b89de5cc17ad8f3e":{
      "scriptId":"u70"},
    "edf02dbd2f9c4757a038ba25498359f8":{
      "scriptId":"u71"}}});