$axure.loadCurrentPage({
  "url":"特派员专家－概览.html",
  "generationDate":new Date(1400740445093.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1a7191004eab4dafbf56248ddd0aad82",
    "type":"Axure:Page",
    "name":"特派员专家－概览",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d109f707c0164f0a9c3d72027ce055a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":64},
            "size":{
              "width":1439,
              "height":58},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dda7621d7f934603b373398af843a116",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":64},
                "size":{
                  "width":1439,
                  "height":58},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u0.png"}},
{
          "id":"8c809d8cae8a408e99010788327832cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":3},
            "size":{
              "width":1439,
              "height":61},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca882fdea57b40719f519e42d6631347",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2,
                  "y":3},
                "size":{
                  "width":1439,
                  "height":61},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u2.png"}},
{
          "id":"32ec6ea7194c4646ad9565ff6e4cf179",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":124},
            "size":{
              "width":120,
              "height":112},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6aa4b12b22b4450db943aeacd328a6b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":266,
                  "y":124},
                "size":{
                  "width":120,
                  "height":112},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u4.png"}},
{
          "id":"ce20e9b198c24f1dad7515b3ce184fd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":446,
              "y":157},
            "size":{
              "width":689,
              "height":51},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95bf0c8db95b4f3fb5f7d7aadc9423cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":446,
                  "y":157},
                "size":{
                  "width":689,
                  "height":51},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0bdfa2ad204643a1af7b282aa73586fa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":477,
              "y":256},
            "size":{
              "width":473,
              "height":43},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ad194857d564551aae1c7a929b218af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":477,
                  "y":256},
                "size":{
                  "width":473,
                  "height":43},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u8.png"}},
{
          "id":"6ffcfebce05e448aaf33ea70e5b7670f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":918,
              "y":282},
            "size":{
              "width":269,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ffd0b123c7e482fb087514ea0bfd38f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":918,
                  "y":282},
                "size":{
                  "width":269,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u10.png"}},
{
          "id":"4b18bea4fe064021a5402c1c66d43263",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":251},
            "size":{
              "width":964,
              "height":3},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88745999f32d40dc8d47dc8e07685455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":251},
                "size":{
                  "width":964,
                  "height":3},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u12.png"}},
{
          "id":"9f1f7242fc3b4de282c3a1e5945b677d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":599,
              "y":815},
            "size":{
              "width":544,
              "height":82},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83770d7708fd47b1aba7e09b5c945d5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":599,
                  "y":815},
                "size":{
                  "width":544,
                  "height":82},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u14.png"}},
{
          "id":"b6794218092046d98a43f4ccaeac0a76",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":481,
              "y":297},
            "size":{
              "width":706,
              "height":624},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64c4dd307e54442bb3740fa8b121ed68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":481,
                  "y":297},
                "size":{
                  "width":706,
                  "height":624},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u16.png"}},
{
          "id":"99a8564fb5984caf8c68a9dc4445dac8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":618},
            "size":{
              "width":251,
              "height":306},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f808494d45242c78f7a9847c722a795",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":618},
                "size":{
                  "width":251,
                  "height":306},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u18.png"}},
{
          "id":"26e7a1209d3e418aa29d32413aa9cd26",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":229,
              "y":266},
            "size":{
              "width":248,
              "height":105},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bca82cb9081242eda41faafd2dbed993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":229,
                  "y":266},
                "size":{
                  "width":248,
                  "height":105},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u20.png"}},
{
          "id":"32ea00d392404b7db17f7d72c6267cf5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":226,
              "y":926},
            "size":{
              "width":255,
              "height":55},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8ba5dabc99c48808c097accf5a5a163",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":926},
                "size":{
                  "width":255,
                  "height":55},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u22.png"}},
{
          "id":"30e87589be2b47dea1610cfbe48ef9e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":914},
            "size":{
              "width":707,
              "height":64},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8c69a4d84f247d9a4ce8692687ea568",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":914},
                "size":{
                  "width":707,
                  "height":64},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u24.png"}},
{
          "id":"3e15a7af3a234556861b6be5147e6148",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":986},
            "size":{
              "width":1376,
              "height":105},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d015a4675464e5f902101f74bd3f6a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":986},
                "size":{
                  "width":1376,
                  "height":105},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u26.png"}},
{
          "id":"c6a13b31f91549d4be7d5c6e93a3e46c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1310,
              "y":985},
            "size":{
              "width":133,
              "height":107},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4c56e06873d4abfb6e226d556372871",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1310,
                  "y":985},
                "size":{
                  "width":133,
                  "height":107},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u28.png"}},
{
          "id":"e6675dd1dd1e4f0690e246e5a9fab3cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":3},
            "size":{
              "width":1009,
              "height":117}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39ed945eeb2241db8ae94b2e1f9606f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":3},
                "size":{
                  "width":1009,
                  "height":117}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u30.png"}},
{
          "id":"3f338b76fb254f1aa2f783019462b86e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":415},
            "size":{
              "width":252,
              "height":197},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff0aa685cf26414ba3779880665f4ca0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":415},
                "size":{
                  "width":252,
                  "height":197},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u32.png"}},
{
          "id":"a270935a1fa644968e9eba51a0d48dab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'黑体 Regular', '黑体'",
            "fontSize":"28px",
            "location":{
              "x":237,
              "y":82},
            "size":{
              "width":275,
              "height":32},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e640c31452c4ea99c7e1e345744d21b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'黑体 Regular', '黑体'",
                "fontSize":"28px",
                "location":{
                  "x":237,
                  "y":82},
                "size":{
                  "width":275,
                  "height":32},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bc915adb70a46cd8d9c89b16e957c99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":748,
              "y":30},
            "size":{
              "width":52,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74eb364dfc3c44b3a772083c907ac72d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":748,
                  "y":30},
                "size":{
                  "width":52,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 科特派服务角 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"科特派服务角.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42bbe148a011446c9eafb1adbd7e8a07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":538,
              "y":474},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5e1ab15c8d041beb456e13a1a2d30bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":538,
                  "y":474},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 特派员专家－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"特派员专家－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67e50f0a78f0457dab745f5adaa510d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":588,
              "y":415},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f1ef3be1fac48fcbb623dc5a6e22d59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":588,
                  "y":415},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 特派员专家－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"特派员专家－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55a3822b96884f4fb2fa4352b4a28b65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":588,
              "y":620},
            "size":{
              "width":52,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28d640129d1f4cbf9d60a67df9f66651",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":588,
                  "y":620},
                "size":{
                  "width":52,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 特派员专家－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"特派员专家－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dda25030f9784246a8a1b134e6a9d115",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":379},
            "size":{
              "width":255,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8df4d962b8ae49b8810d88cc5410049a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":379},
                "size":{
                  "width":255,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u44.png"}},
{
          "id":"013fa9c4c1e247fdbd6a11e4713907f1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":943,
              "y":271},
            "size":{
              "width":245,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07001cc9f904497f820204247f528d65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":943,
                  "y":271},
                "size":{
                  "width":245,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u46.png"}},
{
          "id":"c992af426663424b814996a7a9a6389b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":226,
              "y":251},
            "size":{
              "width":984,
              "height":829}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e7506de7e774e7f8781825915ce1c0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":251},
                "size":{
                  "width":984,
                  "height":829}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u48.png"}},
{
          "id":"b4f0864417f046f4a0a9c4341ffc9c48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":24},
            "size":{
              "width":52,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8897d55f3a7d48ca8eafb364d9151888",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":950,
                  "y":24},
                "size":{
                  "width":52,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ec59ca36a4b4f73a49e4e6c8e6c409c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":869,
              "y":218},
            "size":{
              "width":318,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d155354099a54a8180bd6b1737de9680",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":869,
                  "y":218},
                "size":{
                  "width":318,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u52.png"}},
{
          "id":"ac5d92854bc4469fb35c0c63be306103",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":538,
              "y":474},
            "size":{
              "width":132,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19493a6966684d5b830f0b28534ff78b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":538,
                  "y":474},
                "size":{
                  "width":132,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 特派员专家－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"特派员专家－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a6b3689de4f4e6da5c2fd2458a3b38a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":748,
              "y":474},
            "size":{
              "width":132,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23d71e9fe9ba43469e320f7ee1bf3bf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":748,
                  "y":474},
                "size":{
                  "width":132,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 特派员专家－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"特派员专家－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26b818390e9a4d4aac0a8b6f26a3d69d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":986,
              "y":474},
            "size":{
              "width":132,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dd67cf6cc314d8f95535e0db112c7f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":986,
                  "y":474},
                "size":{
                  "width":132,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 特派员专家－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"特派员专家－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9a4767726ee4e1faaf29c7123943429",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":458,
              "y":650},
            "size":{
              "width":132,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e51bbfb419124b848fe4ce0f6ddaa42a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":458,
                  "y":650},
                "size":{
                  "width":132,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 特派员专家－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"特派员专家－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ad174707c9c44f29aba6adda3577956",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":648,
              "y":650},
            "size":{
              "width":132,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e64ced5c2f114be48d9362cb571f7986",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":648,
                  "y":650},
                "size":{
                  "width":132,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 特派员专家－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"特派员专家－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5ffbbf08ab7436194f6b5eb1b8b2a16",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1070,
              "y":401},
            "size":{
              "width":48,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5b0d800614548fd98b63ab40106ec0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1070,
                  "y":401},
                "size":{
                  "width":48,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u64.png"}},
{
          "id":"1930cedc5e734a9ab0ff17efdbc68107",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":1078,
              "y":404},
            "size":{
              "width":31,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b4d09688b4043d6b3c7e8b1d539bae9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":1078,
                  "y":404},
                "size":{
                  "width":31,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d109f707c0164f0a9c3d72027ce055a5":{
      "scriptId":"u0"},
    "dda7621d7f934603b373398af843a116":{
      "scriptId":"u1"},
    "8c809d8cae8a408e99010788327832cd":{
      "scriptId":"u2"},
    "ca882fdea57b40719f519e42d6631347":{
      "scriptId":"u3"},
    "32ec6ea7194c4646ad9565ff6e4cf179":{
      "scriptId":"u4"},
    "6aa4b12b22b4450db943aeacd328a6b9":{
      "scriptId":"u5"},
    "ce20e9b198c24f1dad7515b3ce184fd4":{
      "scriptId":"u6"},
    "95bf0c8db95b4f3fb5f7d7aadc9423cd":{
      "scriptId":"u7"},
    "0bdfa2ad204643a1af7b282aa73586fa":{
      "scriptId":"u8"},
    "1ad194857d564551aae1c7a929b218af":{
      "scriptId":"u9"},
    "6ffcfebce05e448aaf33ea70e5b7670f":{
      "scriptId":"u10"},
    "6ffd0b123c7e482fb087514ea0bfd38f":{
      "scriptId":"u11"},
    "4b18bea4fe064021a5402c1c66d43263":{
      "scriptId":"u12"},
    "88745999f32d40dc8d47dc8e07685455":{
      "scriptId":"u13"},
    "9f1f7242fc3b4de282c3a1e5945b677d":{
      "scriptId":"u14"},
    "83770d7708fd47b1aba7e09b5c945d5c":{
      "scriptId":"u15"},
    "b6794218092046d98a43f4ccaeac0a76":{
      "scriptId":"u16"},
    "64c4dd307e54442bb3740fa8b121ed68":{
      "scriptId":"u17"},
    "99a8564fb5984caf8c68a9dc4445dac8":{
      "scriptId":"u18"},
    "0f808494d45242c78f7a9847c722a795":{
      "scriptId":"u19"},
    "26e7a1209d3e418aa29d32413aa9cd26":{
      "scriptId":"u20"},
    "bca82cb9081242eda41faafd2dbed993":{
      "scriptId":"u21"},
    "32ea00d392404b7db17f7d72c6267cf5":{
      "scriptId":"u22"},
    "c8ba5dabc99c48808c097accf5a5a163":{
      "scriptId":"u23"},
    "30e87589be2b47dea1610cfbe48ef9e5":{
      "scriptId":"u24"},
    "a8c69a4d84f247d9a4ce8692687ea568":{
      "scriptId":"u25"},
    "3e15a7af3a234556861b6be5147e6148":{
      "scriptId":"u26"},
    "4d015a4675464e5f902101f74bd3f6a5":{
      "scriptId":"u27"},
    "c6a13b31f91549d4be7d5c6e93a3e46c":{
      "scriptId":"u28"},
    "d4c56e06873d4abfb6e226d556372871":{
      "scriptId":"u29"},
    "e6675dd1dd1e4f0690e246e5a9fab3cb":{
      "scriptId":"u30"},
    "39ed945eeb2241db8ae94b2e1f9606f4":{
      "scriptId":"u31"},
    "3f338b76fb254f1aa2f783019462b86e":{
      "scriptId":"u32"},
    "ff0aa685cf26414ba3779880665f4ca0":{
      "scriptId":"u33"},
    "a270935a1fa644968e9eba51a0d48dab":{
      "scriptId":"u34"},
    "4e640c31452c4ea99c7e1e345744d21b":{
      "scriptId":"u35"},
    "9bc915adb70a46cd8d9c89b16e957c99":{
      "scriptId":"u36"},
    "74eb364dfc3c44b3a772083c907ac72d":{
      "scriptId":"u37"},
    "42bbe148a011446c9eafb1adbd7e8a07":{
      "scriptId":"u38"},
    "f5e1ab15c8d041beb456e13a1a2d30bb":{
      "scriptId":"u39"},
    "67e50f0a78f0457dab745f5adaa510d9":{
      "scriptId":"u40"},
    "1f1ef3be1fac48fcbb623dc5a6e22d59":{
      "scriptId":"u41"},
    "55a3822b96884f4fb2fa4352b4a28b65":{
      "scriptId":"u42"},
    "28d640129d1f4cbf9d60a67df9f66651":{
      "scriptId":"u43"},
    "dda25030f9784246a8a1b134e6a9d115":{
      "scriptId":"u44"},
    "8df4d962b8ae49b8810d88cc5410049a":{
      "scriptId":"u45"},
    "013fa9c4c1e247fdbd6a11e4713907f1":{
      "scriptId":"u46"},
    "07001cc9f904497f820204247f528d65":{
      "scriptId":"u47"},
    "c992af426663424b814996a7a9a6389b":{
      "scriptId":"u48"},
    "8e7506de7e774e7f8781825915ce1c0d":{
      "scriptId":"u49"},
    "b4f0864417f046f4a0a9c4341ffc9c48":{
      "scriptId":"u50"},
    "8897d55f3a7d48ca8eafb364d9151888":{
      "scriptId":"u51"},
    "8ec59ca36a4b4f73a49e4e6c8e6c409c":{
      "scriptId":"u52"},
    "d155354099a54a8180bd6b1737de9680":{
      "scriptId":"u53"},
    "ac5d92854bc4469fb35c0c63be306103":{
      "scriptId":"u54"},
    "19493a6966684d5b830f0b28534ff78b":{
      "scriptId":"u55"},
    "2a6b3689de4f4e6da5c2fd2458a3b38a":{
      "scriptId":"u56"},
    "23d71e9fe9ba43469e320f7ee1bf3bf7":{
      "scriptId":"u57"},
    "26b818390e9a4d4aac0a8b6f26a3d69d":{
      "scriptId":"u58"},
    "1dd67cf6cc314d8f95535e0db112c7f3":{
      "scriptId":"u59"},
    "e9a4767726ee4e1faaf29c7123943429":{
      "scriptId":"u60"},
    "e51bbfb419124b848fe4ce0f6ddaa42a":{
      "scriptId":"u61"},
    "3ad174707c9c44f29aba6adda3577956":{
      "scriptId":"u62"},
    "e64ced5c2f114be48d9362cb571f7986":{
      "scriptId":"u63"},
    "d5ffbbf08ab7436194f6b5eb1b8b2a16":{
      "scriptId":"u64"},
    "f5b0d800614548fd98b63ab40106ec0f":{
      "scriptId":"u65"},
    "1930cedc5e734a9ab0ff17efdbc68107":{
      "scriptId":"u66"},
    "8b4d09688b4043d6b3c7e8b1d539bae9":{
      "scriptId":"u67"}}});