$axure.loadCurrentPage({
  "url":"科特派服务角.html",
  "generationDate":new Date(1400740444968.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e768272df3b74246b1396bf577261c80",
    "type":"Axure:Page",
    "name":"科特派服务角",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8f8ed2ecf30946f5a9f5e99c9e1a990b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":3},
            "size":{
              "width":1275,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65e0d0b0f44a40828ed44d1cc6fc01ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2,
                  "y":3},
                "size":{
                  "width":1275,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/科特派服务角/u0.png"}},
{
          "id":"c7a9aa82110246f1bf7ae91086632775",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":346,
              "y":185},
            "size":{
              "width":77,
              "height":75},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c8e5de3b72846ceabb0c84901d3560a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":346,
                  "y":185},
                "size":{
                  "width":77,
                  "height":75},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 特派员专家－概览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"特派员专家－概览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14df77a27a56458b88ae369737d92588",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":723,
              "y":185},
            "size":{
              "width":84,
              "height":75},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c15ab78a7814da18bc8028d4383e87c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":723,
                  "y":185},
                "size":{
                  "width":84,
                  "height":75},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 成果展示－概览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"成果展示－概览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e8b0d777d31424fa89f10883e301736",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":466,
              "y":185},
            "size":{
              "width":84,
              "height":75},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9028e5f2297a46b3a1368c45c7b404e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":466,
                  "y":185},
                "size":{
                  "width":84,
                  "height":75},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 技术需求－概览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"技术需求－概览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b201088654245ccbc6076554819330e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":185},
            "size":{
              "width":84,
              "height":75},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78b34f0f4625432dab0702481da9c93a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":185},
                "size":{
                  "width":84,
                  "height":75},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 企业展示－概览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"企业展示－概览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5945c23ab0664ae88a0bfa42545136af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":846,
              "y":185},
            "size":{
              "width":84,
              "height":75},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8b68a728d8d43898f0cfa2cd7902794",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":846,
                  "y":185},
                "size":{
                  "width":84,
                  "height":75},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 登陆页面 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"登陆页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8f8ed2ecf30946f5a9f5e99c9e1a990b":{
      "scriptId":"u0"},
    "65e0d0b0f44a40828ed44d1cc6fc01ee":{
      "scriptId":"u1"},
    "c7a9aa82110246f1bf7ae91086632775":{
      "scriptId":"u2"},
    "6c8e5de3b72846ceabb0c84901d3560a":{
      "scriptId":"u3"},
    "14df77a27a56458b88ae369737d92588":{
      "scriptId":"u4"},
    "5c15ab78a7814da18bc8028d4383e87c":{
      "scriptId":"u5"},
    "6e8b0d777d31424fa89f10883e301736":{
      "scriptId":"u6"},
    "9028e5f2297a46b3a1368c45c7b404e6":{
      "scriptId":"u7"},
    "1b201088654245ccbc6076554819330e":{
      "scriptId":"u8"},
    "78b34f0f4625432dab0702481da9c93a":{
      "scriptId":"u9"},
    "5945c23ab0664ae88a0bfa42545136af":{
      "scriptId":"u10"},
    "d8b68a728d8d43898f0cfa2cd7902794":{
      "scriptId":"u11"}}});