$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1400740444828.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7430e4c7e7fe419986d153b3be2f7427",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"81366ff8a686400785afc08169c8af9a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":2},
            "size":{
              "width":1375,
              "height":695},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63fc286615bd43c78d4f3496d5b74365",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":2},
                "size":{
                  "width":1375,
                  "height":695},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"6887c6daf6014e8eb2e84ab3786ca132",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":344,
              "y":156},
            "size":{
              "width":327,
              "height":91},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e610a763ba89428da61bc4369da65f8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":156},
                "size":{
                  "width":327,
                  "height":91},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"b5879a9f7c574628a9fc99865f39e10a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":82},
            "size":{
              "width":134,
              "height":86},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28cdefd56e854871bf8bb7bdd022abd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":82},
                "size":{
                  "width":134,
                  "height":86},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"f53d135589344b629f5735c325b71388",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":758,
              "y":94},
            "size":{
              "width":211,
              "height":28},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ad133988c5743ed97f72fe2a2dd9e16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":758,
                  "y":94},
                "size":{
                  "width":211,
                  "height":28},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u6.png"}},
{
          "id":"d31700dff9a24352bf0c8af10069272d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":759,
              "y":122},
            "size":{
              "width":206,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a6810f1a8b949ca888d2c566130653a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":759,
                  "y":122},
                "size":{
                  "width":206,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u8.png"}},
{
          "id":"d7c8c720e19d462fb671d015c5cabee4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'方正黑体_GBK Bold', '方正黑体_GBK'",
            "fontSize":"25px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":784,
              "y":106},
            "size":{
              "width":179,
              "height":28},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb33d12dc9544bebb3846789a7a732bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'方正黑体_GBK Bold', '方正黑体_GBK'",
                "fontSize":"25px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":784,
                  "y":106},
                "size":{
                  "width":179,
                  "height":28},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 科特派服务角 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"科特派服务角.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a20f80785ec47b4b1c517a77e3144aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'方正黑体_GBK Bold', '方正黑体_GBK'",
            "fontSize":"28px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":286,
              "y":159},
            "size":{
              "width":238,
              "height":31},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6267ce85b7f4c6e93b6052515b2fef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'方正黑体_GBK Bold', '方正黑体_GBK'",
                "fontSize":"28px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":286,
                  "y":159},
                "size":{
                  "width":238,
                  "height":31},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0afd4a210514f958609ef8894035071",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":717,
              "y":205},
            "size":{
              "width":302,
              "height":64},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18d433277beb4b938c5e26a8d096d9e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":717,
                  "y":205},
                "size":{
                  "width":302,
                  "height":64},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u14.png"}},
{
          "id":"a311a734f4214de38a8dce7805a62149",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'方正黑体_GBK Bold', '方正黑体_GBK'",
            "fontSize":"25px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":768,
              "y":222},
            "size":{
              "width":218,
              "height":28},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e5109da77c64c08b0064b18038189da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'方正黑体_GBK Bold', '方正黑体_GBK'",
                "fontSize":"25px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":768,
                  "y":222},
                "size":{
                  "width":218,
                  "height":28},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1785ac9aa8a445ba9679328476e2d50e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":335,
              "y":645},
            "size":{
              "width":152,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"982573a607874daf818319d369a463bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":335,
                  "y":645},
                "size":{
                  "width":152,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u18.png"}},
{
          "id":"5256a255a9b34e79848d7069c13e85a3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":644},
            "size":{
              "width":157,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a343212b467242e0bafd1ad799290df3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":644},
                "size":{
                  "width":157,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"eb452ecccba743b2893ce876223584de",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":887,
              "y":643},
            "size":{
              "width":164,
              "height":17},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cedefd4114a9430ca1faa8ffc44b053b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":887,
                  "y":643},
                "size":{
                  "width":164,
                  "height":17},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u20.png"}},
{
          "id":"b07c7550f4c94134b4692aa8b6b08d67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":377,
              "y":646},
            "size":{
              "width":93,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9affecc47d1341d6a51cb90b2acba837",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":377,
                  "y":646},
                "size":{
                  "width":93,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83d7209351d04301bdffd8c010c5b02d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"14px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":645,
              "y":646},
            "size":{
              "width":109,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fd1fd31a2824f628918a5dfd7669d60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"14px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":645,
                  "y":646},
                "size":{
                  "width":109,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48c75b64240b4ad98d1952bed8b9927b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":283,
              "y":89},
            "size":{
              "width":163,
              "height":62},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06d265aae523490fa1d9b4a8c6381207",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":283,
                  "y":89},
                "size":{
                  "width":163,
                  "height":62},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u28.png"}},
{
          "id":"6b7b1e0a705a4eea8a57a6c77e93521f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":31},
            "size":{
              "width":23,
              "height":38},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7f54a6fbe7f4886bb8b8db09664eb78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":31},
                "size":{
                  "width":23,
                  "height":38},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u30.png"}},
{
          "id":"e02729449f2a49c38156f74c71d12792",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":303,
              "y":591},
            "size":{
              "width":781,
              "height":42},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67ec9dd7b9e24fc29e8f7b6556170587",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":303,
                  "y":591},
                "size":{
                  "width":781,
                  "height":42},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u32.png"}},
{
          "id":"86e823384420440fbda48f012ca1d923",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":640},
            "size":{
              "width":766,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5f63033cd8b44b69d9ff7551af80799",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":640},
                "size":{
                  "width":766,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u34.png"}},
{
          "id":"94a645319186447886716b0062238829",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":726,
              "y":205},
            "size":{
              "width":274,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5f3c31b3fe64914bf495b3194680982",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":726,
                  "y":205},
                "size":{
                  "width":274,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 科技资源 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"科技资源.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dafb9136a5bf473591465f467f0e0f17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":604},
            "size":{
              "width":157,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b531f79434b4cdcba08486a96b738b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":604},
                "size":{
                  "width":157,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open http://www.hljkjt.gov.cn in Current Window",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://www.hljkjt.gov.cn",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7ffc53b6461441fba1e898d333d06dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":335,
              "y":604},
            "size":{
              "width":152,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2987e778986248db9a91a5fd52faf241",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":335,
                  "y":604},
                "size":{
                  "width":152,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open http://www.most.gov.cn in Current Window",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://www.most.gov.cn",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdb285866cf946648b8b3e10b16251ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":898,
              "y":604},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"672b7ec92b7b40b7a93aa32c4f01e054",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":898,
                  "y":604},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open http://www.keji123.org in Current Window",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://www.keji123.org",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "81366ff8a686400785afc08169c8af9a":{
      "scriptId":"u0"},
    "63fc286615bd43c78d4f3496d5b74365":{
      "scriptId":"u1"},
    "6887c6daf6014e8eb2e84ab3786ca132":{
      "scriptId":"u2"},
    "e610a763ba89428da61bc4369da65f8b":{
      "scriptId":"u3"},
    "b5879a9f7c574628a9fc99865f39e10a":{
      "scriptId":"u4"},
    "28cdefd56e854871bf8bb7bdd022abd2":{
      "scriptId":"u5"},
    "f53d135589344b629f5735c325b71388":{
      "scriptId":"u6"},
    "3ad133988c5743ed97f72fe2a2dd9e16":{
      "scriptId":"u7"},
    "d31700dff9a24352bf0c8af10069272d":{
      "scriptId":"u8"},
    "6a6810f1a8b949ca888d2c566130653a":{
      "scriptId":"u9"},
    "d7c8c720e19d462fb671d015c5cabee4":{
      "scriptId":"u10"},
    "eb33d12dc9544bebb3846789a7a732bc":{
      "scriptId":"u11"},
    "9a20f80785ec47b4b1c517a77e3144aa":{
      "scriptId":"u12"},
    "d6267ce85b7f4c6e93b6052515b2fef6":{
      "scriptId":"u13"},
    "e0afd4a210514f958609ef8894035071":{
      "scriptId":"u14"},
    "18d433277beb4b938c5e26a8d096d9e2":{
      "scriptId":"u15"},
    "a311a734f4214de38a8dce7805a62149":{
      "scriptId":"u16"},
    "1e5109da77c64c08b0064b18038189da":{
      "scriptId":"u17"},
    "1785ac9aa8a445ba9679328476e2d50e":{
      "scriptId":"u18"},
    "982573a607874daf818319d369a463bb":{
      "scriptId":"u19"},
    "5256a255a9b34e79848d7069c13e85a3":{
      "scriptId":"u20"},
    "a343212b467242e0bafd1ad799290df3":{
      "scriptId":"u21"},
    "eb452ecccba743b2893ce876223584de":{
      "scriptId":"u22"},
    "cedefd4114a9430ca1faa8ffc44b053b":{
      "scriptId":"u23"},
    "b07c7550f4c94134b4692aa8b6b08d67":{
      "scriptId":"u24"},
    "9affecc47d1341d6a51cb90b2acba837":{
      "scriptId":"u25"},
    "83d7209351d04301bdffd8c010c5b02d":{
      "scriptId":"u26"},
    "2fd1fd31a2824f628918a5dfd7669d60":{
      "scriptId":"u27"},
    "48c75b64240b4ad98d1952bed8b9927b":{
      "scriptId":"u28"},
    "06d265aae523490fa1d9b4a8c6381207":{
      "scriptId":"u29"},
    "6b7b1e0a705a4eea8a57a6c77e93521f":{
      "scriptId":"u30"},
    "d7f54a6fbe7f4886bb8b8db09664eb78":{
      "scriptId":"u31"},
    "e02729449f2a49c38156f74c71d12792":{
      "scriptId":"u32"},
    "67ec9dd7b9e24fc29e8f7b6556170587":{
      "scriptId":"u33"},
    "86e823384420440fbda48f012ca1d923":{
      "scriptId":"u34"},
    "d5f63033cd8b44b69d9ff7551af80799":{
      "scriptId":"u35"},
    "94a645319186447886716b0062238829":{
      "scriptId":"u36"},
    "c5f3c31b3fe64914bf495b3194680982":{
      "scriptId":"u37"},
    "dafb9136a5bf473591465f467f0e0f17":{
      "scriptId":"u38"},
    "7b531f79434b4cdcba08486a96b738b3":{
      "scriptId":"u39"},
    "f7ffc53b6461441fba1e898d333d06dc":{
      "scriptId":"u40"},
    "2987e778986248db9a91a5fd52faf241":{
      "scriptId":"u41"},
    "fdb285866cf946648b8b3e10b16251ab":{
      "scriptId":"u42"},
    "672b7ec92b7b40b7a93aa32c4f01e054":{
      "scriptId":"u43"}}});