$axure.loadCurrentPage({
  "url":"企业展示－细览.html",
  "generationDate":new Date(1400740445781.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"94e71e7e2f3749c6859947a8ee56c514",
    "type":"Axure:Page",
    "name":"企业展示－细览",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d109f707c0164f0a9c3d72027ce055a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":64},
            "size":{
              "width":1439,
              "height":58},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dda7621d7f934603b373398af843a116",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":64},
                "size":{
                  "width":1439,
                  "height":58},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u0.png"}},
{
          "id":"8c809d8cae8a408e99010788327832cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":3},
            "size":{
              "width":1439,
              "height":61},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca882fdea57b40719f519e42d6631347",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2,
                  "y":3},
                "size":{
                  "width":1439,
                  "height":61},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u2.png"}},
{
          "id":"7e97076cb2454ac7803d2ce9ef3288e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "location":{
              "x":857,
              "y":78},
            "size":{
              "width":329,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"096f555997b047a88e6c7a8c272c1095",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "location":{
                  "x":857,
                  "y":78},
                "size":{
                  "width":329,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b37bb027272942fb94887b04f28af549",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":242,
              "y":13},
            "size":{
              "width":134,
              "height":42},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b88caed335b345e2aa1c0a996a04e8b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":242,
                  "y":13},
                "size":{
                  "width":134,
                  "height":42},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－细览/u6.png"}},
{
          "id":"5d61b83adc2e4c309dc46633573d5f22",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":957,
              "y":23},
            "size":{
              "width":201,
              "height":21},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b361d03b6d0e4e3eaad5fdf057c2cc34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":957,
                  "y":23},
                "size":{
                  "width":201,
                  "height":21},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－细览/u8.png"}},
{
          "id":"f099d11b8da34dee902b26c67c56bb3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "location":{
              "x":930,
              "y":97},
            "size":{
              "width":137,
              "height":15},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26ff158be6f04765bb4adecf9f0af2cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "location":{
                  "x":930,
                  "y":97},
                "size":{
                  "width":137,
                  "height":15},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd04ed5a1f6a4c25a685fc0f29b2f599",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'黑体 Regular', '黑体'",
            "fontSize":"28px",
            "location":{
              "x":384,
              "y":18},
            "size":{
              "width":346,
              "height":32},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"392b52f079c941bf926ec8189c2ca9eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'黑体 Regular', '黑体'",
                "fontSize":"28px",
                "location":{
                  "x":384,
                  "y":18},
                "size":{
                  "width":346,
                  "height":32},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"372809ed3d8648fbb486d9690548064c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":116},
            "size":{
              "width":964,
              "height":3},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"485e6d9e195b43d48c587aa5fabf0915",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":116},
                "size":{
                  "width":964,
                  "height":3},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u12.png"}},
{
          "id":"4b18bea4fe064021a5402c1c66d43263",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":247},
            "size":{
              "width":964,
              "height":3},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88745999f32d40dc8d47dc8e07685455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":247},
                "size":{
                  "width":964,
                  "height":3},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u12.png"}},
{
          "id":"b4ad8ac69f784a0b9cb7fc5ffdc25636",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":959,
              "y":27},
            "size":{
              "width":58,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7acb5d4747e4451a95883fb03e4ab68f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":959,
                  "y":27},
                "size":{
                  "width":58,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 科特派服务角 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"科特派服务角.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92f09f168c4a47b0a641ad60e5b263fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":740,
              "y":33},
            "size":{
              "width":86,
              "height":18},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d548eac13fb4cae852466ab65810a1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":740,
                  "y":33},
                "size":{
                  "width":86,
                  "height":18},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 科特派服务角 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"科特派服务角.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29df04dee6a04035b2deba082e98358c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":64},
            "size":{
              "width":964,
              "height":3},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86a2a63b6c014474a132ab6e5fef513f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":64},
                "size":{
                  "width":964,
                  "height":3},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u12.png"}},
{
          "id":"26e7a1209d3e418aa29d32413aa9cd26",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":237,
              "y":583},
            "size":{
              "width":233,
              "height":102},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bca82cb9081242eda41faafd2dbed993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":237,
                  "y":583},
                "size":{
                  "width":233,
                  "height":102},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u20.png"}},
{
          "id":"3e15a7af3a234556861b6be5147e6148",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":922},
            "size":{
              "width":1376,
              "height":105},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d015a4675464e5f902101f74bd3f6a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":922},
                "size":{
                  "width":1376,
                  "height":105},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u26.png"}},
{
          "id":"c6a13b31f91549d4be7d5c6e93a3e46c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1310,
              "y":985},
            "size":{
              "width":133,
              "height":107},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4c56e06873d4abfb6e226d556372871",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1310,
                  "y":985},
                "size":{
                  "width":133,
                  "height":107},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u28.png"}},
{
          "id":"32c8e07af03b4dfbad4fb882a4dfe3d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":755,
              "y":904},
            "size":{
              "width":10,
              "height":10},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abf2bf92904c4526a66c44bb615adcf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":755,
                  "y":904},
                "size":{
                  "width":10,
                  "height":10},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－细览/u32.png"}},
{
          "id":"f8fa9ec6351c48bdb6ffcf83f5a13c78",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":223,
              "y":691},
            "size":{
              "width":247,
              "height":52},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dfeedeb714847b79aff74d25fb8ba94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":223,
                  "y":691},
                "size":{
                  "width":247,
                  "height":52},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－细览/u34.png"}},
{
          "id":"f1454fbba6e840fbb3ff6ed1ed2090c6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":242,
              "y":251},
            "size":{
              "width":954,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9766b2d7afe34c9fb0bd8ef6c2c5950d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":242,
                  "y":251},
                "size":{
                  "width":954,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－细览/u38.png"}},
{
          "id":"31fa12f202044df09fad7b1bbbd38478",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":316,
              "y":258},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06db3130dca14f18baedfdc52767c102",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":316,
                  "y":258},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 科特派服务角 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"科特派服务角.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a55fd0b7d8de4bc0a005f8d3943743bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":258},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13a0654fa11d4038b221aac12a16440a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":258},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 企业展示－概览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"企业展示－概览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"138c4e5177d0414ca97d500aeb4ae2bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":258},
            "size":{
              "width":66,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4abc53a892934d6fa1c8351cabab572a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":258},
                "size":{
                  "width":66,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc9903e5bc8a426189c06a07eeb98335",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":423,
              "y":257},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90096f5688bd4ce5a026d7c3023f9455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":423,
                  "y":257},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"160a34ef62854c3289587657924a86bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":242,
              "y":284},
            "size":{
              "width":228,
              "height":289}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c1307372651440c90e078ab4bc159b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":242,
                  "y":284},
                "size":{
                  "width":228,
                  "height":289}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成果展示－细览/u46.png"}},
{
          "id":"14f7c0d639204f258dc66ec9a79e6c7a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":471,
              "y":285},
            "size":{
              "width":725,
              "height":525}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95625b0efe18410391d99ec49de2c929",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":471,
                  "y":285},
                "size":{
                  "width":725,
                  "height":525}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术需求－细览/u52.png"}},
{
          "id":"5ae2e65ca66c4eaeb2b71e2cf6fe2e9a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":291},
            "size":{
              "width":118,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4767a38e8da941edb9025a4757867eb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":291},
                "size":{
                  "width":118,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术需求－细览/u54.png"}},
{
          "id":"11026caafdd1411c9faf716e19236725",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":761,
              "y":373},
            "size":{
              "width":179,
              "height":153}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce9b3469aa974f6385bd8a37c2ffbc27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":761,
                  "y":373},
                "size":{
                  "width":179,
                  "height":153}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术需求－细览/u58.png"}},
{
          "id":"8eac2cf0910742948f0f1c27e722c419",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":976,
              "y":370},
            "size":{
              "width":134,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c431bc1e31a543d5a15a3893c56b927b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":976,
                  "y":370},
                "size":{
                  "width":134,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术需求－细览/u60.png"}},
{
          "id":"417c9b96ca214c0784b1b591c8b39a82",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":664.5,
              "y":291},
            "size":{
              "width":191,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4189ffb84e7a4c3c8b7e4169fd540919",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":664.5,
                  "y":291},
                "size":{
                  "width":191,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术需求－细览/u62.png"}},
{
          "id":"17fcff9ea71c4bdb91ff81dd696a37f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":855,
              "y":291},
            "size":{
              "width":125,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e71174846a84ef9b6021d9550ad74cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":855,
                  "y":291},
                "size":{
                  "width":125,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术需求－细览/u64.png"}},
{
          "id":"e273ea980d9e404698d0199d95fec055",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":583},
            "size":{
              "width":520,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34a1353506b1476d8b766c9309a5ddb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":583},
                "size":{
                  "width":520,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术需求－细览/u66.png"}},
{
          "id":"bfbb7af6900a4405a6642c22edfed8f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":620},
            "size":{
              "width":680,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91f83c04af25482f8c7366229a6a1080",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":620},
                "size":{
                  "width":680,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术需求－细览/u68.png"}},
{
          "id":"728a92a6893e475f8f8d4d0a6a5477eb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1010,
              "y":586},
            "size":{
              "width":160,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef3937543ce64b108ab27d4051eb1cc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1010,
                  "y":586},
                "size":{
                  "width":160,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术需求－细览/u70.png"}},
{
          "id":"032240d0b64847abbae94c47ad2a1e7c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":316,
              "y":291},
            "size":{
              "width":144,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9531e5ecc7f49e99bb9dacdb14e64b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":316,
                  "y":291},
                "size":{
                  "width":144,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/企业展示－细览/u64.png"}},
{
          "id":"5d673bd152dd426ea5b7e53948ac1d62",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":664,
              "y":294},
            "size":{
              "width":206,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8b0a2617a8e44d8924c0b394b67cbb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":664,
                  "y":294},
                "size":{
                  "width":206,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/企业展示－细览/u64.png"}},
{
          "id":"eafdb43b0bb94ad79c6d90e133d8c204",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":763,
              "y":364},
            "size":{
              "width":409,
              "height":185}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9a1c649c2b84bbf85b9e03fc46c5309",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":763,
                  "y":364},
                "size":{
                  "width":409,
                  "height":185}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/企业展示－细览/u68.png"}},
{
          "id":"bf36f4c679f445f0b34eba0d1e1036a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1111,
              "y":339},
            "size":{
              "width":39,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8fa4185003b4968bd33362039e3ed6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1111,
                  "y":339},
                "size":{
                  "width":39,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/企业展示－细览/u70.png"}},
{
          "id":"2155b3f5e4014d1bb599f26c12588da5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":583},
            "size":{
              "width":676,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3300df5c75ca47a7a40bedecd6c87761",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":583},
                "size":{
                  "width":676,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/企业展示－细览/u72.png"}},
{
          "id":"13323f3672894b9eb0a8a3fcdfd4d993",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'黑体 Regular', '黑体'",
            "fontSize":"28px",
            "location":{
              "x":237,
              "y":82},
            "size":{
              "width":353,
              "height":32},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fb9ee5113a348b2aec428886601e6f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'黑体 Regular', '黑体'",
                "fontSize":"28px",
                "location":{
                  "x":237,
                  "y":82},
                "size":{
                  "width":353,
                  "height":32},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e4820d995f7436db80131636ab8b591",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":446,
              "y":157},
            "size":{
              "width":689,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fae4e68cd394c9db5bf1508dd9c0716",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":446,
                  "y":157},
                "size":{
                  "width":689,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6e415f32412489c9d5af7f79fc42ca8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":120},
            "size":{
              "width":131,
              "height":126}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1d680513e66462a9147223f17d924f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":120},
                "size":{
                  "width":131,
                  "height":126}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/企业展示－概览/u38.png"}},
{
          "id":"c0253beca31e4dfcab82977fb13b63be",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":526,
              "y":547},
            "size":{
              "width":114,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b2cc1afe9b541b7aae6d2f8985c154a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":526,
                  "y":547},
                "size":{
                  "width":114,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/企业展示－细览/u80.png"}},
{
          "id":"381e13b853fd40eba16bda31ad77dae5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":608,
              "y":930},
            "size":{
              "width":192,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32089b28b9524766bf3ea7a7e17b59da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":608,
                  "y":930},
                "size":{
                  "width":192,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 科技资源 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"科技资源.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d109f707c0164f0a9c3d72027ce055a5":{
      "scriptId":"u0"},
    "dda7621d7f934603b373398af843a116":{
      "scriptId":"u1"},
    "8c809d8cae8a408e99010788327832cd":{
      "scriptId":"u2"},
    "ca882fdea57b40719f519e42d6631347":{
      "scriptId":"u3"},
    "7e97076cb2454ac7803d2ce9ef3288e2":{
      "scriptId":"u4"},
    "096f555997b047a88e6c7a8c272c1095":{
      "scriptId":"u5"},
    "b37bb027272942fb94887b04f28af549":{
      "scriptId":"u6"},
    "b88caed335b345e2aa1c0a996a04e8b4":{
      "scriptId":"u7"},
    "5d61b83adc2e4c309dc46633573d5f22":{
      "scriptId":"u8"},
    "b361d03b6d0e4e3eaad5fdf057c2cc34":{
      "scriptId":"u9"},
    "f099d11b8da34dee902b26c67c56bb3e":{
      "scriptId":"u10"},
    "26ff158be6f04765bb4adecf9f0af2cc":{
      "scriptId":"u11"},
    "bd04ed5a1f6a4c25a685fc0f29b2f599":{
      "scriptId":"u12"},
    "392b52f079c941bf926ec8189c2ca9eb":{
      "scriptId":"u13"},
    "372809ed3d8648fbb486d9690548064c":{
      "scriptId":"u14"},
    "485e6d9e195b43d48c587aa5fabf0915":{
      "scriptId":"u15"},
    "4b18bea4fe064021a5402c1c66d43263":{
      "scriptId":"u16"},
    "88745999f32d40dc8d47dc8e07685455":{
      "scriptId":"u17"},
    "b4ad8ac69f784a0b9cb7fc5ffdc25636":{
      "scriptId":"u18"},
    "7acb5d4747e4451a95883fb03e4ab68f":{
      "scriptId":"u19"},
    "92f09f168c4a47b0a641ad60e5b263fc":{
      "scriptId":"u20"},
    "1d548eac13fb4cae852466ab65810a1e":{
      "scriptId":"u21"},
    "29df04dee6a04035b2deba082e98358c":{
      "scriptId":"u22"},
    "86a2a63b6c014474a132ab6e5fef513f":{
      "scriptId":"u23"},
    "26e7a1209d3e418aa29d32413aa9cd26":{
      "scriptId":"u24"},
    "bca82cb9081242eda41faafd2dbed993":{
      "scriptId":"u25"},
    "3e15a7af3a234556861b6be5147e6148":{
      "scriptId":"u26"},
    "4d015a4675464e5f902101f74bd3f6a5":{
      "scriptId":"u27"},
    "c6a13b31f91549d4be7d5c6e93a3e46c":{
      "scriptId":"u28"},
    "d4c56e06873d4abfb6e226d556372871":{
      "scriptId":"u29"},
    "32c8e07af03b4dfbad4fb882a4dfe3d4":{
      "scriptId":"u30"},
    "abf2bf92904c4526a66c44bb615adcf4":{
      "scriptId":"u31"},
    "f8fa9ec6351c48bdb6ffcf83f5a13c78":{
      "scriptId":"u32"},
    "5dfeedeb714847b79aff74d25fb8ba94":{
      "scriptId":"u33"},
    "f1454fbba6e840fbb3ff6ed1ed2090c6":{
      "scriptId":"u34"},
    "9766b2d7afe34c9fb0bd8ef6c2c5950d":{
      "scriptId":"u35"},
    "31fa12f202044df09fad7b1bbbd38478":{
      "scriptId":"u36"},
    "06db3130dca14f18baedfdc52767c102":{
      "scriptId":"u37"},
    "a55fd0b7d8de4bc0a005f8d3943743bb":{
      "scriptId":"u38"},
    "13a0654fa11d4038b221aac12a16440a":{
      "scriptId":"u39"},
    "138c4e5177d0414ca97d500aeb4ae2bd":{
      "scriptId":"u40"},
    "4abc53a892934d6fa1c8351cabab572a":{
      "scriptId":"u41"},
    "fc9903e5bc8a426189c06a07eeb98335":{
      "scriptId":"u42"},
    "90096f5688bd4ce5a026d7c3023f9455":{
      "scriptId":"u43"},
    "160a34ef62854c3289587657924a86bc":{
      "scriptId":"u44"},
    "9c1307372651440c90e078ab4bc159b9":{
      "scriptId":"u45"},
    "14f7c0d639204f258dc66ec9a79e6c7a":{
      "scriptId":"u46"},
    "95625b0efe18410391d99ec49de2c929":{
      "scriptId":"u47"},
    "5ae2e65ca66c4eaeb2b71e2cf6fe2e9a":{
      "scriptId":"u48"},
    "4767a38e8da941edb9025a4757867eb8":{
      "scriptId":"u49"},
    "11026caafdd1411c9faf716e19236725":{
      "scriptId":"u50"},
    "ce9b3469aa974f6385bd8a37c2ffbc27":{
      "scriptId":"u51"},
    "8eac2cf0910742948f0f1c27e722c419":{
      "scriptId":"u52"},
    "c431bc1e31a543d5a15a3893c56b927b":{
      "scriptId":"u53"},
    "417c9b96ca214c0784b1b591c8b39a82":{
      "scriptId":"u54"},
    "4189ffb84e7a4c3c8b7e4169fd540919":{
      "scriptId":"u55"},
    "17fcff9ea71c4bdb91ff81dd696a37f0":{
      "scriptId":"u56"},
    "9e71174846a84ef9b6021d9550ad74cf":{
      "scriptId":"u57"},
    "e273ea980d9e404698d0199d95fec055":{
      "scriptId":"u58"},
    "34a1353506b1476d8b766c9309a5ddb0":{
      "scriptId":"u59"},
    "bfbb7af6900a4405a6642c22edfed8f2":{
      "scriptId":"u60"},
    "91f83c04af25482f8c7366229a6a1080":{
      "scriptId":"u61"},
    "728a92a6893e475f8f8d4d0a6a5477eb":{
      "scriptId":"u62"},
    "ef3937543ce64b108ab27d4051eb1cc4":{
      "scriptId":"u63"},
    "032240d0b64847abbae94c47ad2a1e7c":{
      "scriptId":"u64"},
    "c9531e5ecc7f49e99bb9dacdb14e64b0":{
      "scriptId":"u65"},
    "5d673bd152dd426ea5b7e53948ac1d62":{
      "scriptId":"u66"},
    "d8b0a2617a8e44d8924c0b394b67cbb9":{
      "scriptId":"u67"},
    "eafdb43b0bb94ad79c6d90e133d8c204":{
      "scriptId":"u68"},
    "e9a1c649c2b84bbf85b9e03fc46c5309":{
      "scriptId":"u69"},
    "bf36f4c679f445f0b34eba0d1e1036a1":{
      "scriptId":"u70"},
    "b8fa4185003b4968bd33362039e3ed6b":{
      "scriptId":"u71"},
    "2155b3f5e4014d1bb599f26c12588da5":{
      "scriptId":"u72"},
    "3300df5c75ca47a7a40bedecd6c87761":{
      "scriptId":"u73"},
    "13323f3672894b9eb0a8a3fcdfd4d993":{
      "scriptId":"u74"},
    "3fb9ee5113a348b2aec428886601e6f8":{
      "scriptId":"u75"},
    "2e4820d995f7436db80131636ab8b591":{
      "scriptId":"u76"},
    "4fae4e68cd394c9db5bf1508dd9c0716":{
      "scriptId":"u77"},
    "b6e415f32412489c9d5af7f79fc42ca8":{
      "scriptId":"u78"},
    "e1d680513e66462a9147223f17d924f4":{
      "scriptId":"u79"},
    "c0253beca31e4dfcab82977fb13b63be":{
      "scriptId":"u80"},
    "4b2cc1afe9b541b7aae6d2f8985c154a":{
      "scriptId":"u81"},
    "381e13b853fd40eba16bda31ad77dae5":{
      "scriptId":"u82"},
    "32089b28b9524766bf3ea7a7e17b59da":{
      "scriptId":"u83"}}});