$axure.loadCurrentPage({
  "url":"技术需求－概览.html",
  "generationDate":new Date(1400740445453.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2750bf0dc6734e9681961a407b23da55",
    "type":"Axure:Page",
    "name":"技术需求－概览",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e59499ee040c4b82b0fdf57651e6fc48",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":477,
              "y":270},
            "size":{
              "width":719,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e94e397104d409abb60dbbcb4ab333f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":477,
                  "y":270},
                "size":{
                  "width":719,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术需求－概览/u0.png"}},
{
          "id":"d109f707c0164f0a9c3d72027ce055a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":64},
            "size":{
              "width":1439,
              "height":58},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dda7621d7f934603b373398af843a116",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":64},
                "size":{
                  "width":1439,
                  "height":58},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u0.png"}},
{
          "id":"8c809d8cae8a408e99010788327832cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":3},
            "size":{
              "width":1439,
              "height":61},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca882fdea57b40719f519e42d6631347",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2,
                  "y":3},
                "size":{
                  "width":1439,
                  "height":61},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u2.png"}},
{
          "id":"ce20e9b198c24f1dad7515b3ce184fd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Regular', '宋体'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":446,
              "y":163},
            "size":{
              "width":689,
              "height":34},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95bf0c8db95b4f3fb5f7d7aadc9423cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Regular', '宋体'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":446,
                  "y":163},
                "size":{
                  "width":689,
                  "height":34},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b18bea4fe064021a5402c1c66d43263",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":251},
            "size":{
              "width":964,
              "height":3},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88745999f32d40dc8d47dc8e07685455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":251},
                "size":{
                  "width":964,
                  "height":3},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u12.png"}},
{
          "id":"99a8564fb5984caf8c68a9dc4445dac8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":618},
            "size":{
              "width":251,
              "height":306},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f808494d45242c78f7a9847c722a795",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":618},
                "size":{
                  "width":251,
                  "height":306},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u18.png"}},
{
          "id":"26e7a1209d3e418aa29d32413aa9cd26",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":229,
              "y":266},
            "size":{
              "width":248,
              "height":105},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bca82cb9081242eda41faafd2dbed993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":229,
                  "y":266},
                "size":{
                  "width":248,
                  "height":105},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u20.png"}},
{
          "id":"32ea00d392404b7db17f7d72c6267cf5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":226,
              "y":917},
            "size":{
              "width":255,
              "height":55},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8ba5dabc99c48808c097accf5a5a163",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":917},
                "size":{
                  "width":255,
                  "height":55},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u22.png"}},
{
          "id":"3e15a7af3a234556861b6be5147e6148",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":986},
            "size":{
              "width":1376,
              "height":105},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d015a4675464e5f902101f74bd3f6a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":986},
                "size":{
                  "width":1376,
                  "height":105},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u26.png"}},
{
          "id":"c6a13b31f91549d4be7d5c6e93a3e46c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1310,
              "y":985},
            "size":{
              "width":133,
              "height":107},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4c56e06873d4abfb6e226d556372871",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1310,
                  "y":985},
                "size":{
                  "width":133,
                  "height":107},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u28.png"}},
{
          "id":"e6675dd1dd1e4f0690e246e5a9fab3cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":3},
            "size":{
              "width":1009,
              "height":117}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39ed945eeb2241db8ae94b2e1f9606f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":3},
                "size":{
                  "width":1009,
                  "height":117}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u30.png"}},
{
          "id":"3f338b76fb254f1aa2f783019462b86e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":415},
            "size":{
              "width":252,
              "height":197},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff0aa685cf26414ba3779880665f4ca0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":415},
                "size":{
                  "width":252,
                  "height":197},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u32.png"}},
{
          "id":"a270935a1fa644968e9eba51a0d48dab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'黑体 Regular', '黑体'",
            "fontSize":"28px",
            "location":{
              "x":237,
              "y":82},
            "size":{
              "width":353,
              "height":32},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e640c31452c4ea99c7e1e345744d21b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'黑体 Regular', '黑体'",
                "fontSize":"28px",
                "location":{
                  "x":237,
                  "y":82},
                "size":{
                  "width":353,
                  "height":32},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"544c310322e74dbd8c16bc7020fc90ee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":379},
            "size":{
              "width":255,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b68b455f07024f3fa71e27e572e79b13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":379},
                "size":{
                  "width":255,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u44.png"}},
{
          "id":"7215c6d3c11f441ca711b3cc22e325e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":947,
              "y":274},
            "size":{
              "width":245,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5653624dd4d456684de0933e3a585e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":947,
                  "y":274},
                "size":{
                  "width":245,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特派员专家－概览/u46.png"}},
{
          "id":"ceb84cac52034f468df3a776305a6333",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":495,
              "y":958},
            "size":{
              "width":695,
              "height":6}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfae678ca25941f09c2c0eb533320202",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":495,
                  "y":958},
                "size":{
                  "width":695,
                  "height":6}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成果展示－概览/u42.png"}},
{
          "id":"56c2de696e9e416bb77d9b71e34a78ca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":120},
            "size":{
              "width":123,
              "height":126}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b18aa9eebefe4f5da00067ebb5ee34b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":120},
                "size":{
                  "width":123,
                  "height":126}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术需求－概览/u32.png"}},
{
          "id":"9bc915adb70a46cd8d9c89b16e957c99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":748,
              "y":30},
            "size":{
              "width":52,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74eb364dfc3c44b3a772083c907ac72d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":748,
                  "y":30},
                "size":{
                  "width":52,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 科特派服务角 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"科特派服务角.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2a91daaa3f34d549e12a983bcadc0fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'宋体 Bold', '宋体'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066CC,
              "opacity":1},
            "location":{
              "x":494,
              "y":282},
            "size":{
              "width":63,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c17400afd1794936a0d0486f3b172d48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'宋体 Bold', '宋体'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066CC,
                  "opacity":1},
                "location":{
                  "x":494,
                  "y":282},
                "size":{
                  "width":63,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3823349ba05f4d379182ad25eca1fbef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":481,
              "y":300},
            "size":{
              "width":719,
              "height":672}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c56ff0adf644c0390587d3fd983b6aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":481,
                  "y":300},
                "size":{
                  "width":719,
                  "height":672}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术需求－概览/u38.png"}},
{
          "id":"a37aded07e064f9f9a7e64e7e0941f73",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":307},
            "size":{
              "width":213,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbdc3d6e6d5e49308c6748e181be5220",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":494,
                  "y":307},
                "size":{
                  "width":213,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 技术需求－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"技术需求－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/技术需求－概览/u40.png"}},
{
          "id":"046b07a40bc2477aac209823859beee0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":521,
              "y":367},
            "size":{
              "width":190,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29a1bd2a89ac42f08f3aedbe8bd9543b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":521,
                  "y":367},
                "size":{
                  "width":190,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术需求－概览/u42.png"}},
{
          "id":"c184993f716c463a8bf887bc28434ee4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":958,
              "y":26},
            "size":{
              "width":52,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"888f3c90f20847168495f7864a7de5af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":958,
                  "y":26},
                "size":{
                  "width":52,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84a890393cbb4be384570dac4f2fc98e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":316},
            "size":{
              "width":180,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f29d16d887b242fe82ea0ac95ad0bacd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":316},
                "size":{
                  "width":180,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 技术需求－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"技术需求－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1aab96c349c84dbfbc265cc25ba508b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":316},
            "size":{
              "width":180,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de47ab23da82446f9600917022220f38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":316},
                "size":{
                  "width":180,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 技术需求－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"技术需求－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9aa502475fc4a708c37f6cf563c7290",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":990,
              "y":520},
            "size":{
              "width":180,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58d90c5010bf4448bad802f20fecb70c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":990,
                  "y":520},
                "size":{
                  "width":180,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 技术需求－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"技术需求－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d38bb392be645aa9b84ec77d8de06f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":752,
              "y":520},
            "size":{
              "width":180,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b85380328eeb453db1a8104b3a7ca39f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":752,
                  "y":520},
                "size":{
                  "width":180,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 技术需求－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"技术需求－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27ddae1338754b539f756a4065cd8328",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":520},
            "size":{
              "width":180,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d943a1f53c58498a837cb0c0ac98179a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":520},
                "size":{
                  "width":180,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 技术需求－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"技术需求－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b5600f12f924d6db9fc4307ed98d307",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":726},
            "size":{
              "width":180,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36efbe6a06c845a982a309239b494ceb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":726},
                "size":{
                  "width":180,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 技术需求－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"技术需求－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb63f68cbc83444b915b1e93de1429b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":726},
            "size":{
              "width":180,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82a42a4d30164ab79cff5bda2452ec3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":726},
                "size":{
                  "width":180,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 技术需求－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"技术需求－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"025579c70ea14736877a047695e7bd1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":989.999938964844,
              "y":726},
            "size":{
              "width":180,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19b6be00051140ab866ac96d0b804761",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":989.999938964844,
                  "y":726},
                "size":{
                  "width":180,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 技术需求－细览 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"技术需求－细览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7bf00376c414dd0a3fe4860a344e57b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":266},
            "size":{
              "width":245,
              "height":641}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f2f0090d65d4b7cbf6c4fc99e22ce87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":266},
                "size":{
                  "width":245,
                  "height":641}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/技术需求－概览/u62.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e59499ee040c4b82b0fdf57651e6fc48":{
      "scriptId":"u0"},
    "9e94e397104d409abb60dbbcb4ab333f":{
      "scriptId":"u1"},
    "d109f707c0164f0a9c3d72027ce055a5":{
      "scriptId":"u2"},
    "dda7621d7f934603b373398af843a116":{
      "scriptId":"u3"},
    "8c809d8cae8a408e99010788327832cd":{
      "scriptId":"u4"},
    "ca882fdea57b40719f519e42d6631347":{
      "scriptId":"u5"},
    "ce20e9b198c24f1dad7515b3ce184fd4":{
      "scriptId":"u6"},
    "95bf0c8db95b4f3fb5f7d7aadc9423cd":{
      "scriptId":"u7"},
    "4b18bea4fe064021a5402c1c66d43263":{
      "scriptId":"u8"},
    "88745999f32d40dc8d47dc8e07685455":{
      "scriptId":"u9"},
    "99a8564fb5984caf8c68a9dc4445dac8":{
      "scriptId":"u10"},
    "0f808494d45242c78f7a9847c722a795":{
      "scriptId":"u11"},
    "26e7a1209d3e418aa29d32413aa9cd26":{
      "scriptId":"u12"},
    "bca82cb9081242eda41faafd2dbed993":{
      "scriptId":"u13"},
    "32ea00d392404b7db17f7d72c6267cf5":{
      "scriptId":"u14"},
    "c8ba5dabc99c48808c097accf5a5a163":{
      "scriptId":"u15"},
    "3e15a7af3a234556861b6be5147e6148":{
      "scriptId":"u16"},
    "4d015a4675464e5f902101f74bd3f6a5":{
      "scriptId":"u17"},
    "c6a13b31f91549d4be7d5c6e93a3e46c":{
      "scriptId":"u18"},
    "d4c56e06873d4abfb6e226d556372871":{
      "scriptId":"u19"},
    "e6675dd1dd1e4f0690e246e5a9fab3cb":{
      "scriptId":"u20"},
    "39ed945eeb2241db8ae94b2e1f9606f4":{
      "scriptId":"u21"},
    "3f338b76fb254f1aa2f783019462b86e":{
      "scriptId":"u22"},
    "ff0aa685cf26414ba3779880665f4ca0":{
      "scriptId":"u23"},
    "a270935a1fa644968e9eba51a0d48dab":{
      "scriptId":"u24"},
    "4e640c31452c4ea99c7e1e345744d21b":{
      "scriptId":"u25"},
    "544c310322e74dbd8c16bc7020fc90ee":{
      "scriptId":"u26"},
    "b68b455f07024f3fa71e27e572e79b13":{
      "scriptId":"u27"},
    "7215c6d3c11f441ca711b3cc22e325e3":{
      "scriptId":"u28"},
    "c5653624dd4d456684de0933e3a585e9":{
      "scriptId":"u29"},
    "ceb84cac52034f468df3a776305a6333":{
      "scriptId":"u30"},
    "bfae678ca25941f09c2c0eb533320202":{
      "scriptId":"u31"},
    "56c2de696e9e416bb77d9b71e34a78ca":{
      "scriptId":"u32"},
    "b18aa9eebefe4f5da00067ebb5ee34b0":{
      "scriptId":"u33"},
    "9bc915adb70a46cd8d9c89b16e957c99":{
      "scriptId":"u34"},
    "74eb364dfc3c44b3a772083c907ac72d":{
      "scriptId":"u35"},
    "b2a91daaa3f34d549e12a983bcadc0fa":{
      "scriptId":"u36"},
    "c17400afd1794936a0d0486f3b172d48":{
      "scriptId":"u37"},
    "3823349ba05f4d379182ad25eca1fbef":{
      "scriptId":"u38"},
    "0c56ff0adf644c0390587d3fd983b6aa":{
      "scriptId":"u39"},
    "a37aded07e064f9f9a7e64e7e0941f73":{
      "scriptId":"u40"},
    "dbdc3d6e6d5e49308c6748e181be5220":{
      "scriptId":"u41"},
    "046b07a40bc2477aac209823859beee0":{
      "scriptId":"u42"},
    "29a1bd2a89ac42f08f3aedbe8bd9543b":{
      "scriptId":"u43"},
    "c184993f716c463a8bf887bc28434ee4":{
      "scriptId":"u44"},
    "888f3c90f20847168495f7864a7de5af":{
      "scriptId":"u45"},
    "84a890393cbb4be384570dac4f2fc98e":{
      "scriptId":"u46"},
    "f29d16d887b242fe82ea0ac95ad0bacd":{
      "scriptId":"u47"},
    "1aab96c349c84dbfbc265cc25ba508b3":{
      "scriptId":"u48"},
    "de47ab23da82446f9600917022220f38":{
      "scriptId":"u49"},
    "b9aa502475fc4a708c37f6cf563c7290":{
      "scriptId":"u50"},
    "58d90c5010bf4448bad802f20fecb70c":{
      "scriptId":"u51"},
    "1d38bb392be645aa9b84ec77d8de06f1":{
      "scriptId":"u52"},
    "b85380328eeb453db1a8104b3a7ca39f":{
      "scriptId":"u53"},
    "27ddae1338754b539f756a4065cd8328":{
      "scriptId":"u54"},
    "d943a1f53c58498a837cb0c0ac98179a":{
      "scriptId":"u55"},
    "9b5600f12f924d6db9fc4307ed98d307":{
      "scriptId":"u56"},
    "36efbe6a06c845a982a309239b494ceb":{
      "scriptId":"u57"},
    "fb63f68cbc83444b915b1e93de1429b7":{
      "scriptId":"u58"},
    "82a42a4d30164ab79cff5bda2452ec3d":{
      "scriptId":"u59"},
    "025579c70ea14736877a047695e7bd1a":{
      "scriptId":"u60"},
    "19b6be00051140ab866ac96d0b804761":{
      "scriptId":"u61"},
    "a7bf00376c414dd0a3fe4860a344e57b":{
      "scriptId":"u62"},
    "3f2f0090d65d4b7cbf6c4fc99e22ce87":{
      "scriptId":"u63"}}});